#type_of_cam:
#0---stereo kitti
#1---stereo euroc
#2---T265

type_of_cam: 2

image_width: 848
image_height: 800

image_width_out: 300
image_height_out: 300

cam0_intrinsics: [284.0513916015625, 285.19189453125, 427.4079895019531, 401.1722106933594] #fx fy cx cy
cam0_distortion_coeffs: [-0.0015451919753104448, 0.04006154090166092, -0.03794296830892563, 0.006493294145911932] #k1 k2 r1 r2
cam1_intrinsics: [284.285400390625, 285.2674865722656, 431.7026062011719, 385.2261962890625] #fx fy cx cy
cam1_distortion_coeffs: [0.0007516997284255922, 0.032092008739709854, -0.03002322092652321, 0.004072860814630985] #k1 k2 r1 r2

T_init:
[0, 0, 1, 0,
 -1, 0, 0, 0,
 0, -1, 0, 0,
 0, 0, 0, 1]

T_world_body:
[1,0,0,0,
 0,1,0,0,
 0,0,1,0,
 0,0,0,1]

T_body_cam0:
[0, 0, 1, 0,
-1, 0, 0, 0,
 0, -1, 0, 0,
 0, 0, 0, 1]

T_cam1_cam0:
[9.99994218e-01, -8.26635107e-04, -3.29655036e-03, -6.42428249e-02,
 8.28813005e-04,  9.99999523e-01,  6.59199432e-04, -1.58874827e-05,
 3.29600368e-03, -6.61927043e-04,  9.99994397e-01, 3.78768891e-06,
 0, 0, 0, 1]

#reserved para for future functions
frame_id: map
run_rviz: true
